DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  owner_id INTEGER REFERENCES users(id) NOT NULL,
  name VARCHAR(255) NOT NULL,
  lat FLOAT NOT NULL,
  long FLOAT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  views BIGINT NOT NULL DEFAULT 0
);
